neow3j/neow3j

core/src/test/java/io/neow3j/utils/CollectionTest.java
Hi,
I had a look through this codebase and have written some unit tests with the help of [Diffblue Cover](https://www.diffblue.com/opensource) for the `io.neow3j.utils.Collection` class. Hopefully these tests will help you to spot any regressions in the future.  
Please let me know if you would like any more tests written for other areas of this project (or other projects), I would be happy to help.
=> Added tests for io.neow3j.utils.Collection

core/src/test-integration/java/io/neow3j/protocol/Neow3jTestWrapper.java, crypto/src/main/java/io/neow3j/crypto/Claim.java, crypto/src/main/java/io/neow3j/crypto/transaction/ClaimTransaction.java, crypto/src/main/java/io/neow3j/crypto/transaction/ContractTransaction.java, crypto/src/main/java/io/neow3j/crypto/transaction/RawTransaction.java, crypto/src/main/java/io/neow3j/crypto/transaction/RawTransactionOutput.java, crypto/src/test/java/io/neow3j/crypto/ClaimTransactionTest.java, crypto/src/test/java/io/neow3j/crypto/ContractTransactionTest.java, model/src/main/java/io/neow3j/model/types/TransactionType.java, utils/src/main/java/io/neow3j/utils/Numeric.java
Extended RawTransaction and implemented ClaimTransaction. This resolves #23.
=> Added raw ClaimTransactions

core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java, core/src/main/java/io/neow3j/protocol/core/Neo.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetClaimable.java, core/src/test-integration/java/io/neow3j/protocol/CoreIT.java, core/src/test-integration/java/io/neow3j/protocol/InterfaceCoreIT.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jTestWrapper.java, core/src/test/java/io/neow3j/protocol/core/RequestTest.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
=> Implementation of getclaimable method and tests.

core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java, core/src/main/java/io/neow3j/protocol/core/Neo.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NeoListPlugins.java, core/src/test-integration/java/io/neow3j/protocol/CoreIT.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jTestWrapper.java, core/src/test/java/io/neow3j/protocol/core/RequestTest.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java, model/src/main/java/io/neow3j/model/types/NodePluginType.java
=> Implementation of listplugins RPC method.

crypto/src/main/java/io/neow3j/crypto/transaction/RawTransactionAttribute.java, crypto/src/test/java/io/neow3j/crypto/transaction/RawTransactionAttributeTest.java, model/src/main/java/io/neow3j/model/types/TransactionAttributeUsageType.java
=>  Corrected the transaction attribute serialization

core/src/test/java/io/neow3j/protocol/transaction/ClaimTransactionTest.java, core/src/test/java/io/neow3j/protocol/transaction/ContractTransactionTest.java, crypto/src/main/java/io/neow3j/crypto/transaction/RawTransaction.java
=> Added transaction hash/id method to RawTransaction

wallet/src/main/java/io/neow3j/wallet/Account.java, wallet/src/main/java/io/neow3j/wallet/Wallet.java, wallet/src/test/java/io/neow3j/wallet/AccountTest.java, wallet/src/test/java/io/neow3j/wallet/WalletTest.java
=> #57: Convenience methods for wallet and account creation

contract/src/test/java/io/neow3j/contract/ContractInvocationTest.java, wallet/src/main/java/io/neow3j/wallet/Account.java, wallet/src/main/java/io/neow3j/wallet/AssetTransfer.java, wallet/src/main/java/io/neow3j/wallet/Balances.java, wallet/src/main/java/io/neow3j/wallet/LeftToRightInputCalculationStrategy.java, wallet/src/main/java/io/neow3j/wallet/Utxo.java, wallet/src/test/java/io/neow3j/wallet/AssetTransferTest.java, wallet/src/test/java/io/neow3j/wallet/LeftToRightInputCalculationStrategyTest.java
=> Allow building an AssetTransfer from specific UTXOs.

contract/src/main/java/io/neow3j/contract/NeoToken.java, contract/src/main/java/io/neow3j/contract/SmartContract.java, contract/src/test/java/io/neow3j/contract/SmartContractTest.java
Resolves #120 
These are the last amendments for issue #120.
=> Unit tests for SmartContract class

compiler/src/main/java/io/neow3j/compiler/Compiler.java, devpack/src/main/java/io/neow3j/devpack/framework/Helper.java
=> Fixes for byte array initialization and devpack helper methods

contract/src/main/java/io/neow3j/contract/SmartContract.java
I need these changes to work with the `SmartContract` class in the compiler and I also think that they will be useful for other developers as well.
=> Small changes to the SmartContract API to make development easier

core/src/main/java/io/neow3j/protocol/core/methods/response/BufferStackItem.java, core/src/main/java/io/neow3j/protocol/core/methods/response/PointerStackItem.java, core/src/main/java/io/neow3j/protocol/core/methods/response/StackItem.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
According to #194, in this PR the Buffer and Pointer stack items are implemented.
=> Buffer and Pointer StackItem Implementation

wallet/src/main/java/io/neow3j/wallet/Wallet.java, wallet/src/test/java/io/neow3j/wallet/WalletTest.java
=> Save NEP6 Wallet with custom set name

build.gradle, contract/src/main/java/io/neow3j/contract/NeoToken.java, contract/src/main/java/io/neow3j/contract/Nep5Token.java, contract/src/main/java/io/neow3j/contract/PolicyContract.java, contract/src/main/java/io/neow3j/contract/TransactionBuilder.java, contract/src/test/java/io/neow3j/contract/NeoTokenTest.java, contract/src/test/java/io/neow3j/contract/NeoURITest.java, contract/src/test/java/io/neow3j/contract/Nep5TokenTest.java, contract/src/test/java/io/neow3j/contract/PolicyContractTest.java, contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java, core/build.gradle, core/src/main/java/io/neow3j/transaction/Signer.java, core/src/main/java/io/neow3j/transaction/Witness.java, core/src/test/java/io/neow3j/transaction/WitnessTest.java, crypto/src/main/java/io/neow3j/crypto/ECKeyPair.java, wallet/src/main/java/io/neow3j/wallet/Account.java, wallet/src/main/java/io/neow3j/wallet/Bip39Account.java, wallet/src/main/java/io/neow3j/wallet/Wallet.java, wallet/src/test/java/io/neow3j/wallet/AccountTest.java, wallet/src/test/java/io/neow3j/wallet/Bip39AccountTest.java, wallet/src/test/java/io/neow3j/wallet/WalletTest.java
=> Convenience methods

compiler/src/main/java/io/neow3j/compiler/Compiler.java, compiler/src/main/java/io/neow3j/compiler/CompilerException.java, compiler/src/main/java/io/neow3j/compiler/LocalVariableHelper.java, compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java, compiler/src/main/java/io/neow3j/compiler/NeoMethod.java, compiler/src/main/java/io/neow3j/compiler/NeoModule.java, compiler/src/main/java/io/neow3j/compiler/converters/ArraysConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/BitOperationsConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/JumpsConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/MiscConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
=> Improved error reporting in compiler exceptions

compiler/src/test-integration/java/io/neow3j/compiler/ObjectLengthTest.java, contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java, contract/src/test/resources/responses/getapplicationlog.json, contract/src/test/resources/responses/getapplicationlog_unknowntx.json, core/src/main/java/io/neow3j/transaction/Transaction.java
=> Transaction tracking

compiler/src/main/java/io/neow3j/compiler/converters/MiscConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java, compiler/src/test/java/io/neow3j/compiler/ThrowExceptionTest.java
This is only about throwing exceptions not about the try-catch-finally blocks.
=> compiler support for exception throwing

contract/src/main/java/io/neow3j/contract/NeoURI.java, contract/src/test/java/io/neow3j/contract/NeoURITest.java, contract/src/test/java/io/neow3j/contract/Nep17TokenTest.java
=> NeoURI Transfer Update

contract/src/main/java/io/neow3j/contract/NeoToken.java, contract/src/test/java/io/neow3j/contract/NeoTokenTest.java, contract/src/test/resources/responses/invokefunction_getcandidates.json
=> Candidate check in NeoToken vote method

contract/src/main/java/io/neow3j/contract/ContractUtils.java, gradle-plugin/build.gradle, gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jCompileAction.java, gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jCompileTask.java, gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jPluginOptions.java, gradle-plugin/src/test-integration/java/io/neow3j/devpack/gradle/GradleProjectTestCase.java, gradle-plugin/src/test-integration/java/io/neow3j/devpack/gradle/Neow3jCompilePluginIntegrationTest.java, gradle-plugin/src/test-integration/java/io/neow3j/devpack/gradle/TestCaseUtils.java, gradle-plugin/src/test-integration/resources/ContractTest.java, gradle-plugin/src/test-integration/resources/ContractTestWithDisplayName.java, gradle-plugin/src/test-integration/resources/ContractTestWithError.java, gradle-plugin/src/test/java/io/neow3j/devpack/gradle/Neow3jPluginTest.java
=> Output dir config option in Gradle

compiler/src/main/java/io/neow3j/compiler/Compiler.java, compiler/src/main/java/io/neow3j/compiler/CompilerException.java, compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java, compiler/src/main/java/io/neow3j/compiler/NeoMethod.java, compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java, compiler/src/test/java/io/neow3j/compiler/SafeMethodTest.java, devpack/src/main/java/io/neow3j/devpack/annotations/Safe.java
=> Add @Safe annotation

build.gradle
=> Update bouncy castle version

compiler/src/main/java/io/neow3j/compiler/CompilationUnit.java, compiler/src/main/java/io/neow3j/compiler/Compiler.java, compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java, compiler/src/main/java/io/neow3j/compiler/NeoMethod.java, compiler/src/main/java/io/neow3j/compiler/NeoTryInstruction.java, compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test/java/io/neow3j/compiler/GroupManifestTest.java, compiler/src/test/java/io/neow3j/compiler/PermissionManifestTest.java, compiler/src/test/java/io/neow3j/compiler/TrustManifestTest.java, contract/src/test/java/io/neow3j/contract/ContractUtilsTest.java, core/src/main/java/io/neow3j/protocol/core/methods/response/ContractManifest.java, devpack/src/main/java/io/neow3j/devpack/annotations/Group.java, devpack/src/main/java/io/neow3j/devpack/annotations/Permission.java, devpack/src/main/java/io/neow3j/devpack/annotations/Trust.java
=> Add Groups, Trusts, and Permissions to the contract manifest

contract/src/main/java/io/neow3j/contract/TransactionBuilder.java, contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java, contract/src/test/resources/responses/invokefunction_symbol_neo.json, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
Related to changes made in #394 , #386
=> Fix calculate network fee conversion

compiler/src/test-integration/java/io/neow3j/compiler/VerificationMethodIntegrationTest.java, core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
=> Verification method integration tests

core/src/main/java/io/neow3j/contract/ContractParameter.java, core/src/test/java/io/neow3j/contract/ContractParameterTest.java
=> Convenience Method for Array ContractParameter

contract/src/main/java/io/neow3j/contract/ContractManagement.java, contract/src/main/java/io/neow3j/contract/FungibleToken.java, contract/src/main/java/io/neow3j/contract/NeoToken.java, contract/src/main/java/io/neow3j/contract/NonFungibleToken.java, contract/src/main/java/io/neow3j/contract/RoleManagement.java, contract/src/main/java/io/neow3j/contract/SmartContract.java, contract/src/main/java/io/neow3j/contract/TransactionBuilder.java, contract/src/main/java/io/neow3j/contract/exceptions/InvocationConfigurationException.java, contract/src/main/java/io/neow3j/contract/exceptions/UnexpectedReturnTypeException.java, contract/src/test/java/io/neow3j/contract/ContractManagementTest.java, contract/src/test/java/io/neow3j/contract/ContractTestHelper.java, contract/src/test/java/io/neow3j/contract/ContractUtilsTest.java, contract/src/test/java/io/neow3j/contract/FungibleTokenTest.java, contract/src/test/java/io/neow3j/contract/NefFileTest.java, contract/src/test/java/io/neow3j/contract/NeoTokenTest.java, contract/src/test/java/io/neow3j/contract/NeoURITest.java, contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java, contract/src/test/java/io/neow3j/contract/PolicyContractTest.java, contract/src/test/java/io/neow3j/contract/RoleManagementTest.java, contract/src/test/java/io/neow3j/contract/SmartContractTest.java, contract/src/test/java/io/neow3j/contract/TokenTest.java, contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
=> Data parameter in transfers

core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java, core/src/main/java/io/neow3j/protocol/core/Neo.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java, core/src/test/java/io/neow3j/protocol/core/RequestTest.java
=> Get contract state by name

contract/src/main/java/io/neow3j/contract/ContractManagement.java, core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java, core/src/main/java/io/neow3j/protocol/core/Neo.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NeoBlockHeaderCount.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetContractState.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetNativeContracts.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java, core/src/test/java/io/neow3j/protocol/core/RequestTest.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
=> Add getNativeContracts and getBlockHeaderCount RPC calls

contract/src/main/java/io/neow3j/contract/NeoNameService.java, contract/src/main/java/io/neow3j/contract/NonFungibleToken.java, contract/src/test/java/io/neow3j/contract/NeoNameServiceTest.java, contract/src/test/java/io/neow3j/contract/PolicyContractTest.java, contract/src/test/resources/responses/nft_ownerof.json, contract/src/test/resources/responses/nns_getRecord_typeA.json, contract/src/test/resources/responses/nns_getRecord_typeAAAA.json, contract/src/test/resources/responses/nns_getRecord_typeCNAME.json, contract/src/test/resources/responses/nns_getRecord_typeTXT.json, contract/src/test/resources/responses/nns_invalidOperation_dueToState.json, contract/src/test/resources/responses/nns_invokefunction_getPrice.json, contract/src/test/resources/responses/nns_invokefunction_ownerof.json, contract/src/test/resources/responses/nns_invokefunction_properties.json, contract/src/test/resources/responses/nns_invokefunction_symbol.json, contract/src/test/resources/responses/nns_invokefunction_totalSupply.json, contract/src/test/resources/responses/nns_invokescript_addRoot.json, contract/src/test/resources/responses/nns_returnAny.json, core/src/main/java/io/neow3j/protocol/core/RecordType.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NameState.java, core/src/main/java/io/neow3j/protocol/core/methods/response/TokenState.java
=> Name Service wrapper class

core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java, core/src/main/java/io/neow3j/protocol/core/Neo.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetProof.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetStateHeight.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetStateRoot.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NeoVerifyProof.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java, core/src/test/java/io/neow3j/protocol/core/RequestTest.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
=> Added methods for State Service RPC calls

contract/src/main/java/io/neow3j/contract/NeoNameService.java, contract/src/main/java/io/neow3j/contract/NonFungibleToken.java, contract/src/test/java/io/neow3j/contract/NeoNameServiceTest.java, contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java, contract/src/test/resources/responses/nns_invokefunction_properties.json, core/src/main/java/io/neow3j/protocol/core/methods/response/NFTokenState.java, core/src/main/java/io/neow3j/protocol/core/methods/response/NameState.java
=> Non-fungible token changes

contract/src/main/java/io/neow3j/contract/NeoToken.java, contract/src/main/java/io/neow3j/contract/PolicyContract.java, contract/src/test/java/io/neow3j/contract/NeoTokenTest.java, contract/src/test/java/io/neow3j/contract/PolicyContractTest.java, contract/src/test/resources/responses/invokefunction_getRegisterPrice.json
=> Removed outdated PolicyContract methods and added new NeoToken methods

compiler/src/main/java/io/neow3j/compiler/Compiler.java, compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test-integration/java/io/neow3j/compiler/ContractEventsIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/DeploymentMethodIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java, compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java, compiler/src/test/java/io/neow3j/compiler/ContractEventsTest.java, devpack/src/main/java/io/neow3j/devpack/events/Event.java, devpack/src/main/java/io/neow3j/devpack/events/Event0Arg.java, devpack/src/main/java/io/neow3j/devpack/events/Event10Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event11Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event12Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event13Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event14Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event15Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event16Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event1Arg.java, devpack/src/main/java/io/neow3j/devpack/events/Event2Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event3Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event4Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event5Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event6Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event7Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event8Args.java, devpack/src/main/java/io/neow3j/devpack/events/Event9Args.java, devpack/src/main/java/io/neow3j/devpack/events/EventInterface.java
=> Event refactor

build.gradle
=> Bundle JAR

contract/src/main/java/io/neow3j/contract/ContractManagement.java, contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
Resolves #470.
> The dto `ContractState` is not affected by this. Its properties are all still used by the RPC calls `getcontractstate` and `getnativecontracts`, respectively.
=> Remove getContract from ContractManagement

build.gradle
=> Exclude tests jacoco

core/src/main/java/io/neow3j/contract/ContractParameter.java
=> Remove ContractParameter deserializer

compiler/src/test-integration/java/io/neow3j/compiler/StorageContextIntegrationTest.java, devpack/src/main/java/io/neow3j/devpack/StorageContext.java
And cover the class with tests.
=> Add StorageContext createMap method with String parameter

core/src/main/java/io/neow3j/wallet/nep6/NEP6Account.java, core/src/test/java/io/neow3j/wallet/nep6/NEP6WalletTest.java, core/src/test/resources/wallet/wallet.json
=> Accept isdefault in NEP-6 account deserialization

compiler/src/main/java/io/neow3j/compiler/Compiler.java, compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test-integration/java/io/neow3j/compiler/InstanceOfIntegrationTest.java, compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java, compiler/src/test/java/io/neow3j/compiler/CompilerTest.java, core/src/main/java/io/neow3j/contract/ContractParameter.java
=> Support for instanceof

compiler/src/test-integration/java/io/neow3j/compiler/ArraysConverterIntegrationTest.java
=> Tests for vararg method parameters

core/src/main/java/io/neow3j/protocol/Neow3j.java, core/src/main/java/io/neow3j/protocol/Neow3jConfig.java, core/src/main/java/io/neow3j/protocol/core/response/NeoGetVersion.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
=> Magic/Network as long (uint32)

compiler/src/test-integration/java/io/neow3j/compiler/RuntimeIntegrationTest.java, devpack/src/main/java/io/neow3j/devpack/constants/TriggerType.java
Found that our trigger types were not up to date.
=> Update trigger types

compiler/src/test-integration/java/io/neow3j/compiler/ContractIntegrationTest.java, devpack/src/main/java/io/neow3j/devpack/constants/CallFlags.java
Added javadoc and changed names to camelcase for readability.
=> Update call flags

core/src/main/java/io/neow3j/protocol/core/response/NeoWitness.java, core/src/main/java/io/neow3j/protocol/core/response/Transaction.java, core/src/main/java/io/neow3j/protocol/core/response/TransactionAttribute.java, core/src/main/java/io/neow3j/transaction/Transaction.java
For convenience when we want to print the transaction in readable format.
=> Add toJson method for transaction

compiler/src/main/java/io/neow3j/compiler/NeoMethod.java, compiler/src/test-integration/java/io/neow3j/compiler/ObjectsTest.java, devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java
Solves #577.
There was a problem with setting up methods correctly when they have the `this` object as a parameter.
=> Fix for instance methods bug

compiler/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest2.java, compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest2.java, devpack/src/main/java/io/neow3j/devpack/Storage.java, devpack/src/main/java/io/neow3j/devpack/StorageMap.java
=> Hash160 and Hash256 support in Storage and StorageMap

compiler/src/test/java/io/neow3j/compiler/OnNEP11PaymentMethodTest.java, devpack/src/main/java/io/neow3j/devpack/annotations/OnDeployment.java, devpack/src/main/java/io/neow3j/devpack/annotations/OnNEP11Payment.java, devpack/src/main/java/io/neow3j/devpack/annotations/OnVerification.java
It was not up to date with the latest changes on the NEP-11 standard.
=> Update method signature of onNep11Payment method

core/src/main/java/io/neow3j/transaction/Transaction.java, core/src/main/java/io/neow3j/transaction/TransactionBuilder.java, core/src/test/java/io/neow3j/transaction/TransactionBuilderTest.java, core/src/test/java/io/neow3j/transaction/TransactionTest.java
=> MaxAttributes check and minor changes

compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java, compiler/src/test-integration/java/io/neow3j/compiler/DivisibleNFTIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/NFTIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/NonDivisibleNFTIntegrationTest.java, compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java, core/src/main/java/io/neow3j/protocol/core/stackitem/ByteStringStackItem.java, devpack/src/main/java/io/neow3j/devpack/contracts/DivisibleNonFungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/FungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/NonDivisibleNonFungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/NonFungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/RoleManagement.java, devpack/src/main/java/io/neow3j/devpack/contracts/Token.java
=> Add NFT classes to devpack

compiler/src/test-integration/java/io/neow3j/compiler/DivisibleNFTIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/NFTIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/NNSIntegrationTest.java, devpack/src/main/java/io/neow3j/devpack/contracts/NeoNameService.java
=> Add NameService interface to devpack

compiler/src/main/java/io/neow3j/compiler/Compiler.java, compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java, gradle-plugin/src/test-integration/java/io/neow3j/devpack/gradle/Neow3jCompilePluginIntegrationTest.java
Closes #553 
@csmuller please, take a look at the tests, as well as the changes I've made to the `Compiler.java` file. Thanks!
=> Class compatibility

core/src/main/java/io/neow3j/transaction/AccountSigner.java, core/src/main/java/io/neow3j/transaction/Transaction.java, core/src/main/java/io/neow3j/transaction/TransactionBuilder.java, core/src/main/java/io/neow3j/transaction/WitnessScope.java, core/src/test/java/io/neow3j/transaction/TransactionBuilderTest.java, core/src/test/java/io/neow3j/transaction/TransactionTest.java
=> Neow3j setter in Transaction class

build.gradle, compiler/build.gradle, contract/build.gradle, contract/src/test/java/io/neow3j/contract/NeoURITest.java, core/build.gradle, core/src/main/java/io/neow3j/crypto/ECKeyPair.java, core/src/test/java/io/neow3j/utils/ArrayUtilsTest.java, devpack/build.gradle, gradle-plugin/build.gradle
=> Gradle: change compile to implementation

contract/src/main/java/io/neow3j/contract/FungibleToken.java, contract/src/main/java/io/neow3j/contract/NonFungibleToken.java, contract/src/test/java/io/neow3j/contract/FungibleTokenTest.java, contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java
While adapting the examples I realised the need for transfer methods that take a Hash160 as the 'from' parameter. That allows devs to create transfers from ContractSigners.
=> Add transfer methods with hash instead of account as 'from' parameter

compiler/src/test-integration/java/io/neow3j/compiler/HelperIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/StorageContextIntegrationTest.java, devpack/src/main/java/io/neow3j/devpack/Helper.java, devpack/src/main/java/io/neow3j/devpack/StorageContext.java
=> Add helper method for int to byte[] conversion

.github/workflows/ci-cd.yml, .github/workflows/integration.yml, compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java, compiler/src/test-integration/java/io/neow3j/compiler/TryCatchBlocksTest.java, compiler/src/test/java/io/neow3j/compiler/AssertionTest.java
=> Support getMessage method for caught exception

compiler/src/test-integration/java/io/neow3j/compiler/ByteStringIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java, contract/src/main/java/io/neow3j/contract/NeoToken.java, core/src/main/java/io/neow3j/wallet/Wallet.java, core/src/test/java/io/neow3j/wallet/WalletTest.java, devpack/src/main/java/io/neow3j/devpack/ByteString.java, devpack/src/main/java/io/neow3j/devpack/Helper.java, devpack/src/main/java/io/neow3j/devpack/Storage.java, devpack/src/main/java/io/neow3j/devpack/StorageMap.java
=> Support integer keys in storage methods

core/src/main/java/io/neow3j/protocol/core/response/InvocationResult.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
=> Add pending signature attribute

compiler/src/test-integration/java/io/neow3j/compiler/MapTest.java, core/src/main/java/io/neow3j/script/OpCode.java, core/src/main/java/io/neow3j/script/ScriptBuilder.java, core/src/test/java/io/neow3j/contract/ScriptBuilderTest.java, test-tools/src/main/java/io/neow3j/test/NeoTestContainer.java, test-tools/src/main/resources/neo-cli-config/tokentracker.config.json, test-tools/src/main/resources/test.properties
=> Add new struct and map opcodes

compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java, devpack/src/main/java/io/neow3j/devpack/StorageMap.java
=> Support find in StorageMap

core/src/main/java/io/neow3j/transaction/Transaction.java, core/src/main/java/io/neow3j/transaction/TransactionBuilder.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jWriteIntegrationTest.java, core/src/test-integration/java/io/neow3j/protocol/TransactionBuilderIntegrationTest.java, core/src/test/java/io/neow3j/transaction/TransactionBuilderTest.java
=> Add additional system fee method to TransactionBuilder

contract/src/test-integration/java/io/neow3j/contract/FungibleTokenIntegrationTest.java, core/src/main/java/io/neow3j/crypto/ECKeyPair.java, core/src/main/java/io/neow3j/script/ScriptBuilder.java, core/src/main/java/io/neow3j/script/VerificationScript.java, core/src/main/java/io/neow3j/transaction/Transaction.java, core/src/main/java/io/neow3j/transaction/Witness.java, core/src/main/java/io/neow3j/wallet/Account.java, core/src/test/java/io/neow3j/transaction/TransactionTest.java
=> Ensure correct ordering of signatures

.idea/codeStyles/Project.xml, core/src/main/java/io/neow3j/types/ContractParameter.java, core/src/test/java/io/neow3j/contract/ContractParameterTest.java
=> Add utility method for byte ContractParameter

compiler/src/main/java/io/neow3j/compiler/AsmHelper.java, compiler/src/main/java/io/neow3j/compiler/Compiler.java, compiler/src/main/java/io/neow3j/compiler/NeoMethod.java, compiler/src/main/java/io/neow3j/compiler/SuperNeoMethod.java, compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test-integration/java/io/neow3j/compiler/InstanceInheritanceIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/MapTest.java, compiler/src/test-integration/java/io/neow3j/compiler/NullCheckIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/ObjectsTest.java, compiler/src/test-integration/java/io/neow3j/compiler/StaticVariablesIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/StdLibIntegrationTest.java, compiler/src/test/java/io/neow3j/compiler/StaticVariablesTest.java, compiler/src/test/java/io/neow3j/compiler/sourcelookup/DirectorySourceContainerTest.java, devpack/src/main/java/io/neow3j/devpack/annotations/Struct.java
=> Support instance inheritance

compiler/src/main/java/io/neow3j/compiler/Compiler.java, contract/src/main/java/io/neow3j/contract/NefFile.java, contract/src/test/java/io/neow3j/contract/NefFileTest.java, core/src/main/java/io/neow3j/protocol/core/response/ContractNef.java, core/src/main/java/io/neow3j/protocol/core/response/ContractState.java, core/src/main/java/io/neow3j/protocol/core/response/NativeContractState.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jWriteIntegrationTest.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java, test-tools/src/main/java/io/neow3j/test/NeoTestContainer.java
=> Add field source to ContractNef

core/src/main/java/io/neow3j/protocol/Neow3j.java, core/src/main/java/io/neow3j/protocol/Neow3jConfig.java, core/src/main/java/io/neow3j/transaction/TransactionBuilder.java, core/src/test-integration/java/io/neow3j/protocol/TransactionBuilderIntegrationTest.java, core/src/test/java/io/neow3j/transaction/TransactionBuilderTest.java, core/src/test/resources/responses/invokescript_fault.json
=> Add option to allow transmission on fault

compiler/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java, devpack/src/main/java/io/neow3j/devpack/Storage.java, devpack/src/main/java/io/neow3j/devpack/StorageMap.java
=> Add Storage helper methods for `Hash160` and `Hash256`

compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java, compiler/src/test/java/io/neow3j/compiler/StringLiteralHelperTest.java
=> Enforce String type for String concatenation

compiler/src/test-integration/java/io/neow3j/compiler/ContractTestRule.java, compiler/src/test-integration/java/io/neow3j/compiler/HelperIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/LedgerContractIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/NeoTokenIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/ObjectInheritedIntegrationTest.java, contract/src/main/java/io/neow3j/contract/NeoToken.java, contract/src/test-integration/java/io/neow3j/contract/IntegrationTestHelper.java, contract/src/test-integration/java/io/neow3j/contract/NeoTokenIntegrationTest.java, contract/src/test/java/io/neow3j/contract/NeoTokenTest.java, contract/src/test/resources/responses/invokefunction_getAllCandidates.json, contract/src/test/resources/responses/invokefunction_getCandidateVote.json, core/src/main/java/io/neow3j/script/InteropService.java, core/src/main/java/io/neow3j/script/OpCode.java, core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java, devpack/src/main/java/io/neow3j/devpack/Helper.java, devpack/src/main/java/io/neow3j/devpack/Signer.java, devpack/src/main/java/io/neow3j/devpack/WitnessRule.java, devpack/src/main/java/io/neow3j/devpack/WitnessRuleCondition.java, devpack/src/main/java/io/neow3j/devpack/constants/WitnessRuleAction.java, devpack/src/main/java/io/neow3j/devpack/constants/WitnessRuleConditionType.java, devpack/src/main/java/io/neow3j/devpack/contracts/LedgerContract.java, devpack/src/main/java/io/neow3j/devpack/contracts/NeoToken.java, test-tools/src/main/resources/neo-cli-config/applicationlogs.config.json, test-tools/src/main/resources/neo-cli-config/dbft.config.json, test-tools/src/main/resources/neo-cli-config/oracle.config.json, test-tools/src/main/resources/neo-cli-config/rpcserver.config.json, test-tools/src/main/resources/neo-cli-config/stateservice.config.json, test-tools/src/main/resources/test.properties
=> Update for Neo v3.3.0

compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java, compiler/src/test/java/io/neow3j/compiler/CallFlagsTest.java, devpack/src/main/java/io/neow3j/devpack/annotations/CallFlags.java
=> Add CallFlags annotation to devpack

compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test-integration/java/io/neow3j/compiler/ContractInterfaceIntegrationTest.java, compiler/src/test-integration/java/io/neow3j/compiler/NFTIntegrationTest.java, compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java, compiler/src/test/java/io/neow3j/compiler/ContractInterfaceTest.java, devpack/src/main/java/io/neow3j/devpack/annotations/NativeContract.java, devpack/src/main/java/io/neow3j/devpack/contracts/ContractInterface.java, devpack/src/main/java/io/neow3j/devpack/contracts/ContractManagement.java, devpack/src/main/java/io/neow3j/devpack/contracts/CryptoLib.java, devpack/src/main/java/io/neow3j/devpack/contracts/DivisibleNonFungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/FungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/GasToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/LedgerContract.java, devpack/src/main/java/io/neow3j/devpack/contracts/NeoNameService.java, devpack/src/main/java/io/neow3j/devpack/contracts/NeoToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/NonDivisibleNonFungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/NonFungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/OracleContract.java, devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java, devpack/src/main/java/io/neow3j/devpack/contracts/RoleManagement.java, devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java, devpack/src/main/java/io/neow3j/devpack/contracts/Token.java
Allowing String parameter in ContractInterface ctor (big-endian script hash).
=> Enhance ContractInterface instantiation

compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test/java/io/neow3j/compiler/ECPointTest.java, compiler/src/test/java/io/neow3j/compiler/HashTest.java, core/src/main/java/io/neow3j/crypto/ECKeyPair.java, core/src/test/java/io/neow3j/crypto/ECKeyPairTest.java, devpack/src/main/java/io/neow3j/devpack/ECPoint.java, devpack/src/main/java/io/neow3j/devpack/Hash160.java, devpack/src/main/java/io/neow3j/devpack/Hash256.java, int-tests/src/test-integration/java/io/neow3j/compiler/ECPointIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
=> Support Hash and ECPoint from Constant String

compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java, compiler/src/test/java/io/neow3j/compiler/ECPointTest.java, core/src/main/java/io/neow3j/constants/NeoConstants.java, core/src/main/java/io/neow3j/crypto/ECKeyPair.java, core/src/main/java/io/neow3j/protocol/core/response/ContractManifest.java, core/src/main/java/io/neow3j/types/ContractParameter.java, core/src/main/java/io/neow3j/utils/KeyUtils.java, core/src/test/java/io/neow3j/crypto/ECKeyPairTest.java
=> Allow uncompressed public key in ECPublicKey constructor

build.gradle
Closes #783 
I've tested ECKeyPair functions, sign, recover and verify with a local released version in VS Code.
=> Upgrade bouncycastle

core/src/main/java/io/neow3j/utils/Numeric.java, core/src/test/java/io/neow3j/utils/NumericTest.java
=> Add valid hex check in Numeric class

devpack/src/main/java/io/neow3j/devpack/List.java, int-tests/src/test-integration/java/io/neow3j/compiler/ListIntegrationTest.java
=> Add `List.reverse()`

compiler/src/main/java/io/neow3j/compiler/NeoMethod.java, compiler/src/main/java/io/neow3j/compiler/converters/ArraysConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java, compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test/java/io/neow3j/compiler/CallFlagsTest.java, compiler/src/test/java/io/neow3j/compiler/ContractInterfaceTest.java, core/src/main/java/io/neow3j/script/ScriptBuilder.java
=> Use NEWARRAY0 for empty arrays

compiler/src/main/java/io/neow3j/compiler/NeoMethod.java, contract/src/main/java/io/neow3j/contract/SmartContract.java, contract/src/test/java/io/neow3j/contract/SmartContractTest.java, contract/src/test/resources/responses/invokescript_ownerOf_array.json, core/src/main/java/io/neow3j/script/ScriptBuilder.java, int-tests/src/test-integration/java/io/neow3j/compiler/DivisibleNFTIntegrationTest.java
=> Add method to unwrap iterator

devpack/src/main/java/io/neow3j/devpack/Storage.java, devpack/src/main/java/io/neow3j/devpack/StorageMap.java
=> Optimise conversion to a boolean stack item without using CONVERT

contract/src/main/java/io/neow3j/contract/ContractManagement.java, contract/src/test/java/io/neow3j/contract/ContractManagementTest.java, contract/src/test/resources/responses/contractstate.json, contract/src/test/resources/responses/management_contractstate_notexistent.json, contract/src/test/resources/responses/management_getContract.json, contract/src/test/resources/responses/management_hashes_unwrapped.json, core/src/main/java/io/neow3j/protocol/core/response/ContractState.java, core/src/main/java/io/neow3j/protocol/core/response/RecordState.java, devpack/src/main/java/io/neow3j/devpack/contracts/ContractManagement.java, int-tests/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/contract/ContractManagementIntegrationTest.java
Closes #894 
Closes #895
Closes #893
=> Add getContractById and getContractHashes

core/src/main/java/io/neow3j/script/InteropService.java, devpack/src/main/java/io/neow3j/devpack/Runtime.java, int-tests/src/test-integration/java/io/neow3j/compiler/RuntimeIntegrationTest.java
=> #905: Add syscall System.Runtime.LoadScript

devpack/src/main/java/io/neow3j/devpack/constants/FindOptions.java, int-tests/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java
=> Replace Map.Entry with Iterator.Struct in javadoc and tests

build.gradle, compiler/src/main/java/io/neow3j/compiler/Compiler.java, compiler/src/test/java/io/neow3j/compiler/PlaceholderSubstitutionTest.java, int-tests/src/test-integration/java/io/neow3j/compiler/PlaceholderSubstitutionIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/test/ModuleTest.java, int-tests/src/test-integration/java/io/neow3j/test/TestContract2.java
=> Improve placeholder feature in compiler

build.gradle, compiler/src/main/java/io/neow3j/compiler/Compiler.java, core/src/main/java/io/neow3j/types/NeoVMStateType.java
=> Remove redundant JsonValue annotation in NeoVMStateType

core/src/main/java/io/neow3j/crypto/Sign.java, core/src/test/java/io/neow3j/crypto/SignTest.java
=> Add Sign.recoverV()

compiler/src/main/java/io/neow3j/compiler/NeoMethod.java, compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
=> Fix use of PUSH0/1 instead of PUSHF/T

contract/src/main/java/io/neow3j/contract/NeoToken.java, contract/src/test/java/io/neow3j/contract/NeoTokenTest.java, int-tests/src/test-integration/java/io/neow3j/contract/NeoTokenIntegrationTest.java
=> Add NeoToken utility method for unclaimedGas without block height

devpack/src/main/java/io/neow3j/devpack/Storage.java, devpack/src/main/java/io/neow3j/devpack/StorageMap.java, devpack/src/main/java/io/neow3j/devpack/constants/FindOptions.java, int-tests/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java
=> Add `FindOptions.Backwards`

build.gradle, compiler/src/main/java/io/neow3j/compiler/Compiler.java, core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java, core/src/main/java/io/neow3j/protocol/core/Neo.java, core/src/main/java/io/neow3j/protocol/core/response/ContractStorageEntry.java, core/src/main/java/io/neow3j/protocol/core/response/ExpressContractStorageEntry.java, core/src/main/java/io/neow3j/protocol/core/response/NeoExpressGetContractStorage.java, core/src/main/java/io/neow3j/protocol/core/response/NeoFindStorage.java, core/src/test/java/io/neow3j/protocol/core/RequestTest.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java, int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jExpressIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
=> Support RPC `findstorage`

core/src/main/java/io/neow3j/script/InteropService.java
=> Add javadoc to interop Notify

compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java, compiler/src/test/java/io/neow3j/compiler/AssertionTest.java, core/src/main/java/io/neow3j/script/OpCode.java, devpack/src/main/java/io/neow3j/devpack/Helper.java, int-tests/src/test-integration/java/io/neow3j/compiler/AssertionIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/compiler/HelperIntegrationTest.java
=> Support for `ABORTMSG` and `ASSERTMSG`

devpack/src/main/java/io/neow3j/devpack/Storage.java, devpack/src/main/java/io/neow3j/devpack/StorageMap.java, int-tests/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java
=> Storage Utility Methods for Boolean Values

build.gradle, compiler/src/main/java/io/neow3j/compiler/Compiler.java, devpack/src/main/java/io/neow3j/devpack/Storage.java, devpack/src/main/java/io/neow3j/devpack/StorageMap.java, int-tests/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java
=> Support `Hash160` and `Hash256` as Storage keys

compiler/src/test/java/io/neow3j/compiler/AsmHelperTest.java, devpack/src/main/java/io/neow3j/devpack/ByteString.java, devpack/src/main/java/io/neow3j/devpack/ByteStringType.java, devpack/src/main/java/io/neow3j/devpack/ECPoint.java, devpack/src/main/java/io/neow3j/devpack/Hash160.java, devpack/src/main/java/io/neow3j/devpack/Hash256.java, devpack/src/main/java/io/neow3j/devpack/Storage.java, devpack/src/main/java/io/neow3j/devpack/StorageMap.java, int-tests/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java
=> Introduce abstract `ByteStringType`

.github/workflows/integration.yml, build.gradle, core/build.gradle, core/src/test/java/io/neow3j/wallet/WalletTest.java, int-tests/build.gradle, int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java, neofs/build.gradle, neofs/src/main/java/io/neow3j/neofs/sdk/NeoFSClient.java
=> Dependency updates and other minor changes

core/src/main/java/io/neow3j/protocol/core/response/NeoGetVersion.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java, int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
=> Add `hardforks` to `getversion`

core/src/main/java/io/neow3j/script/InteropService.java, devpack/src/main/java/io/neow3j/devpack/Runtime.java, int-tests/src/test-integration/java/io/neow3j/compiler/RuntimeIntegrationTest.java
=> Add new syscall `currentSigners`

core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java, core/src/main/java/io/neow3j/protocol/core/Neo.java, core/src/main/java/io/neow3j/protocol/core/response/NeoCancelTransaction.java, core/src/test/java/io/neow3j/protocol/core/RequestTest.java, core/src/test/java/io/neow3j/protocol/core/ResponseTest.java, int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jWriteIntegrationTest.java
There's a new issue related to this [here](https://github.com/neow3j/neow3j/issues/1008) if you're interested in some details. Though, you don't necessarily need to look at it for reviewing this PR.
=> Add support for `canceltransaction` RPC method.

DEVELOPMENT.md, README.md, RELEASE.md
=> Release 3.21.2

compiler/src/main/java/io/neow3j/compiler/AsmHelper.java
Introduced a try-with-resources statement for the .class files we're reading using ASM.
I reviewed the whole code in search of potential file read/write leaks.
=> Make sure files are read and closed

test-tools/src/main/java/io/neow3j/test/NeoExpressTestContainer.java, test-tools/src/main/resources/test.properties
...and update how address is extracted from neo-express account create command.
Closes #1014
=> Upgrade neow3j-test-docker version

build.gradle, core/build.gradle
=> Upgrade bouncy castle targeting JDK 1.8 as min version

README.md
Supports dark and light user preferences.
=> Mention 1ClickNode in README file

core/src/main/java/io/neow3j/script/InteropService.java, devpack/src/main/java/io/neow3j/devpack/constants/InteropService.java
Closes #1052 
merge #1050 first
=> Add missing interop service System.Runtime.GetAddressVersion

core/src/main/java/io/neow3j/crypto/Hash.java, core/src/test/java/io/neow3j/crypto/HashTest.java
=> Rename `sha3` methods to `keccak256`

int-tests/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/compiler/StorageContextIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jWriteIntegrationTest.java, test-tools/src/main/java/io/neow3j/test/NeoTestContainer.java, test-tools/src/main/resources/neo-cli-config/applicationlogs.config.json, test-tools/src/main/resources/neo-cli-config/config.json, test-tools/src/main/resources/neo-cli-config/rpcserver.config.json, test-tools/src/main/resources/test.properties
Related to #1036
Resolves #1038
=> Update neo3-privatenet-docker image to v3.7.4

devpack/src/main/java/io/neow3j/devpack/contracts/CryptoLib.java, int-tests/src/test-integration/java/io/neow3j/compiler/CryptoLibIntegrationTest.java
=> Add `CryptoLib.keccak256()`

contract/src/test/java/io/neow3j/contract/RoleManagementTest.java, core/src/main/java/io/neow3j/protocol/core/Role.java, devpack/src/main/java/io/neow3j/devpack/constants/Role.java, int-tests/src/test-integration/java/io/neow3j/contract/RoleManagementIntegrationTest.java
=> Add P2P Notary role

contract/src/main/java/io/neow3j/contract/NeoToken.java, contract/src/test/java/io/neow3j/contract/NeoTokenTest.java, contract/src/test/resources/responses/neoToken_getCommitteeAddress.json, devpack/src/main/java/io/neow3j/devpack/contracts/NeoToken.java, int-tests/src/test-integration/java/io/neow3j/compiler/NeoTokenIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/contract/NeoTokenIntegrationTest.java
=> Add new method `getCommitteeAddress` to NeoToken classes

core/src/main/java/io/neow3j/serialization/BinaryReader.java, core/src/main/java/io/neow3j/serialization/BinaryWriter.java, core/src/test/java/io/neow3j/serialization/BinaryReaderTest.java, core/src/test/java/io/neow3j/serialization/BinaryWriterTest.java
Resolves #1079
This PR adds the following functions:
- `BinaryReader.readUInt64()`
- `BinaryWriter.writeInt16(short)`
- `BinaryWriter.writeUint64(BigInteger)`
=> feat: Add uint64 serialization capabilities

compiler/src/test/java/io/neow3j/compiler/ContractInterfaceTest.java, devpack/src/main/java/io/neow3j/devpack/annotations/CallFlags.java, devpack/src/main/java/io/neow3j/devpack/contracts/ContractManagement.java, devpack/src/main/java/io/neow3j/devpack/contracts/CryptoLib.java, devpack/src/main/java/io/neow3j/devpack/contracts/DivisibleNonFungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/FungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/LedgerContract.java, devpack/src/main/java/io/neow3j/devpack/contracts/NeoNameService.java, devpack/src/main/java/io/neow3j/devpack/contracts/NeoToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/NonDivisibleNonFungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/NonFungibleToken.java, devpack/src/main/java/io/neow3j/devpack/contracts/OracleContract.java, devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java, devpack/src/main/java/io/neow3j/devpack/contracts/RoleManagement.java, devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java, devpack/src/main/java/io/neow3j/devpack/contracts/Token.java, int-tests/src/test-integration/java/io/neow3j/compiler/DivisibleNFTIntegrationTest.java, int-tests/src/test-integration/java/io/neow3j/compiler/NFTIntegrationTest.java
=> Apply more loose default call flags in contract interfaces
