neow3j/neow3j

crypto/src/main/java/io/neow3j/crypto/transaction/RawTransactionInput.java

A serialized transaction must serialize utxo's prevIndex in big-endian,or The transaction will failed unless it's input index was zero.Please confirm this commit.

changed RawTransactionInput prevIndex to big-endian

---

wallet/src/main/java/io/neow3j/wallet/AssetTransfer.java
wallet/src/test/java/io/neow3j/wallet/AssetTransferTest.java

Added methods for constructing an asset transfer with a single output given by assetId, amount, and receiving account. Added related tests. Related to #29.

Convenience methods for AssetTransfer

---

crypto/src/main/java/io/neow3j/crypto/transaction/RawTransactionOutput.java
wallet/src/main/java/io/neow3j/wallet/Account.java
wallet/src/main/java/io/neow3j/wallet/AssetTransfer.java
wallet/src/test/java/io/neow3j/wallet/AssetTransferTest.java

One can now attempt to transfer assets from a smart contracts address. I say 'attempt' because it depends on the smart contract's verification if the transfer will be accepted or not.
```
AssetTransfer at = new AssetTransfer.Builder(neow3jSpy)
.fromContract(contractScriptHash)
...
```

Allow asset transfers from contracts.

---

core/src/main/java/io/neow3j/protocol/core/methods/response/AnyStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/ArrayStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/BooleanStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/ByteStringStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/IntegerStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/InteropInterfaceStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/MapStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/StackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/StructStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/TransactionCosigner.java
core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
core/src/test/java/io/neow3j/protocol/core/methods/response/StackItemTest.java
model/src/main/java/io/neow3j/model/types/StackItemType.java

According to issue #131,  StackItems could potentially be deserialised using Jackson annotations.
Resolves #131

Refactor `StackItem` to use Jackson annotations

---

compiler/src/main/java/io/neow3j/compiler/Compiler.java
compiler/src/test-integration/java/io/neow3j/compiler/ArithmeticOperatorsTest.java
compiler/src/test-integration/resources/responses/ArithmeticOperators/allAssignmentOperators.json

This fixes one point of issue #199.
I can't write tests for all the new code that I added, e.g., for the handling DUP_X2 JVM opcode. I simply don't know which Java code will result in such opcodes.

Fix conversion of JVM's special DUP and POP opcodes.

---

build.gradle
core/src/main/java/io/neow3j/protocol/core/methods/response/AnyStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/BufferStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/ByteStringStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/InteropInterfaceStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/MapStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/StackItem.java
core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
core/src/test/java/io/neow3j/protocol/core/methods/response/StackItemTest.java
core/src/test/java/io/neow3j/protocol/rx/JsonRpc2_0RxTest.java
model/src/main/java/io/neow3j/model/types/StackItemType.java

Corrected the return types to StackItem subtypes of `asAny` and `asInteropInterface`.
Updated dependency testcontainers-java to latest released version (1.15.0). 
Changed deprecated import `Mockito.Matchers` to `Mockito.ArgumentMatchers`.
Closes #228 #252

Update imports and correct returns of StackItem methods

---

compiler/src/test-integration/java/io/neow3j/compiler/BinaryTest.java
compiler/src/test-integration/java/io/neow3j/compiler/ByteArrayTest.java
compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java
contract/src/main/java/io/neow3j/contract/NFToken.java
utils/src/main/java/io/neow3j/contract/ContractParameter.java
utils/src/test/java/io/neow3j/contract/ContractParameterTest.java

@mialbu and I had to adapt the byte array ContractParameter creation method not too long ago because of a bug. I stumbled upon this change again and realized it can be done a bit prettier by putting the Base64 encoding into the `ContractParameter` serializer/deserializer.

Shift Base64 encoding/decoding of byte array ContractParameters to the JSON serializer/deserializer

---

compiler/src/test-integration/java/io/neow3j/compiler/HelperTest.java
devpack/src/main/java/io/neow3j/devpack/Helper.java

Cover helper methods with unit tests.
Added a couple of new methods that manipulate strings and already existed for byte arrays.

Devpack helper methods

---

contract/src/main/java/io/neow3j/contract/Nep5Token.java
contract/src/main/java/io/neow3j/contract/Token.java
contract/src/test/java/io/neow3j/contract/Nep5TokenTest.java
contract/src/test/java/io/neow3j/contract/SmartContractTest.java
contract/src/test/java/io/neow3j/contract/TokenTest.java
contract/src/test/resources/responses/invokefunction_name.json
contract/src/test/resources/responses/invokefunction_symbol.json
contract/src/test/resources/responses/invokefunction_symbol_neo.json

Added a check to throw an exception, when the provided amount has more decimals than the token supports and increased the test coverage of the class `Nep5Token`.
Closes #257

Decimals check for transfers

---

compiler/src/main/java/io/neow3j/compiler/AsmHelper.java
compiler/src/test-integration/java/io/neow3j/compiler/ContractEventsIntegrationTest.java
compiler/src/test/java/io/neow3j/compiler/AsmHelperTest.java

The compilation of events with primitive array type parameters, e.g., `Event2Args<byte[], Integer>` had a bug. The type parameters weren't parsed correctly leading to errors in the manifest and debugging information.

Fix for a bug in the event compilation

---

contract/src/main/java/io/neow3j/contract/ContractUtils.java
contract/src/test/java/io/neow3j/contract/ContractUtilsTest.java
gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jCompileAction.java
gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jPluginUtils.java
gradle-plugin/src/test/java/io/neow3j/devpack/gradle/Neow3jPluginUtilsTest.java

The filenames of the NEF and debug info file are not set according to the name attribute in the manifest. 
I refactored the whole file writing process a bit.

Fix filenames of NEF and debug info files from gradle plugin output

---

core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java

Further, renamed `witnesses` to `signers` in `invokeFunction` method and adapted the mapping lambda expression.

Added JavaDoc to RPC call methods

---

compiler/src/main/java/io/neow3j/compiler/Compiler.java
compiler/src/main/java/io/neow3j/compiler/CompilerException.java
compiler/src/main/java/io/neow3j/compiler/InitsslotNeoMethod.java
compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java

The solution to #311 is that we prohibit usage of local variables in static constructors. The neo-vm does not support them (in the INITSSLOT method, which is the corresponding construct of a static constructor.
The alternative solution would be to parse the static constructor and try to produce neo-vm code without using local variables. Creating such a parser obviously implies much higher effort than the solution of this PR.

Prohibit local variables in static constructor

---

devpack/src/main/java/io/neow3j/devpack/CallFlags.java

Reuse callflag values from contract package in devpack package to avoid having to update callflags in multiple places.

Reuse CallFlags values in devpack 

---

core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
core/src/main/java/io/neow3j/protocol/rx/JsonRpc2_0Rx.java
core/src/main/java/io/neow3j/protocol/rx/Neow3jRx.java
core/src/test/java/io/neow3j/protocol/rx/JsonRpc2_0RxTest.java

This PR adds only a convenience method to subscribe to new incoming blocks.

Add method to subscribe to new blocks without catching up

---

compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
compiler/src/test-integration/java/io/neow3j/compiler/ContractTestRule.java
contract/src/main/java/io/neow3j/contract/NeoURI.java
contract/src/main/java/io/neow3j/contract/SmartContract.java
contract/src/test/java/io/neow3j/contract/FungibleTokenTest.java
core/src/main/java/io/neow3j/contract/ContractParameter.java
core/src/main/java/io/neow3j/contract/Hash160.java
core/src/main/java/io/neow3j/contract/Hash256.java
core/src/main/java/io/neow3j/contract/ScriptBuilder.java
core/src/main/java/io/neow3j/crypto/Hash.java
core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
core/src/main/java/io/neow3j/protocol/core/Neo.java
core/src/main/java/io/neow3j/protocol/core/methods/response/ByteArrayStackItem.java
core/src/main/java/io/neow3j/protocol/core/methods/response/TransactionSendAsset.java
core/src/main/java/io/neow3j/protocol/core/methods/response/TransactionSigner.java
core/src/main/java/io/neow3j/transaction/Signer.java
core/src/main/java/io/neow3j/transaction/Transaction.java
core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
core/src/test-integration/java/io/neow3j/protocol/Neow3jWriteIntegrationTest.java
core/src/test/java/io/neow3j/contract/Hash160Test.java
core/src/test/java/io/neow3j/contract/Hash256Test.java
core/src/test/java/io/neow3j/protocol/core/RequestTest.java
core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
core/src/test/java/io/neow3j/transaction/TransactionTest.java
core/src/test/java/io/neow3j/transaction/WitnessTest.java
core/src/test/java/io/neow3j/wallet/AccountTest.java

The hashes in the classes `Hash160` and `Hash256` are now stored in big-endian format and its constructors now all take big-endian formats as parameter. This way the hashes are uniformly handled in big-endian format.
Resolves #442.

Uniform hash endianness handling

---

compiler/src/test-integration/java/io/neow3j/compiler/IteratorTest.java
compiler/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java
devpack/src/main/java/io/neow3j/devpack/Iterator.java
devpack/src/main/java/io/neow3j/devpack/Map.java
devpack/src/main/java/io/neow3j/devpack/Storage.java

Since the neo-vm returns a StructStackItem when iterating over map entries, I changed the Map.Entry type to Iterator.Struct.

Changed the the Map.Entry to Iterator.Struct

---

compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
compiler/src/test-integration/java/io/neow3j/compiler/ContractInterfacesIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/CryptoLibIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/FungibleTokenTest.java
compiler/src/test-integration/java/io/neow3j/compiler/GasTokenIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/LedgerContractIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/NeoTokenIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/PolicyContractIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/RoleManagementTest.java
compiler/src/test-integration/java/io/neow3j/compiler/StdLibIntegrationTest.java
compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
devpack/src/main/java/io/neow3j/devpack/ContractInterface.java
devpack/src/main/java/io/neow3j/devpack/Hash160.java
devpack/src/main/java/io/neow3j/devpack/Runtime.java

Also, improved the handling of contract interfaces in the compiler.

Make getHash of Contract Interfaces return little-endian hash

---

compiler/src/test-integration/java/io/neow3j/compiler/ECPointIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/SwitchCaseIntegrationTest.java
devpack/src/main/java/io/neow3j/devpack/Block.java
devpack/src/main/java/io/neow3j/devpack/ECPoint.java
devpack/src/main/java/io/neow3j/devpack/Hash160.java
devpack/src/main/java/io/neow3j/devpack/Hash256.java
devpack/src/main/java/io/neow3j/devpack/StringLiteralHelper.java
devpack/src/main/java/io/neow3j/devpack/annotations/OnNEP17Payment.java

I think it is more appropriate to always use 'to' for such conversion methods.

Changed method name from 'as' to 'to'

---

compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
compiler/src/test/java/io/neow3j/compiler/TrustManifestTest.java

In blockchain we trust... The same handling of '0x' that applied to permission contract hashes and public keys is needed for trusts.

More on trusts and permissions

---

.github/workflows/ci-cd.yml
compiler/src/test-integration/java/io/neow3j/compiler/CryptoLibIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/RoleManagementTest.java
devpack/src/main/java/io/neow3j/devpack/Block.java
devpack/src/main/java/io/neow3j/devpack/Contract.java
devpack/src/main/java/io/neow3j/devpack/Hash160.java
devpack/src/main/java/io/neow3j/devpack/Hash256.java
devpack/src/main/java/io/neow3j/devpack/Transaction.java
devpack/src/main/java/io/neow3j/devpack/constants/NamedCurve.java
devpack/src/main/java/io/neow3j/devpack/constants/OracleResponseCode.java
devpack/src/main/java/io/neow3j/devpack/constants/Role.java
devpack/src/main/java/io/neow3j/devpack/contracts/OracleContract.java
devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java
devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java

I know that java's standard for constants is all upper case, but since the devpack is anyway not used for writting standard code and because i think that the camelcase format has better readability, I wanted to have all of them in camelcase with the first letter being upper case.
Some of the constants where already camelcase. This PR standardizes this throughout the whole devpack.
The javadoc changes are not related but I snuck them into this PR anyway since it's not actual code changes.

Standardize the formatting of the devpack's constant names

---

compiler/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
devpack/src/main/java/io/neow3j/devpack/Hash160.java
devpack/src/main/java/io/neow3j/devpack/Hash256.java

When working on the governance contracts i realized that a static 'isValid' method on the hash classes would be more convenient than the instance methods that we provide at the moment. This new 'isValid(Object data)' checks if the hash is either a Buffer or ByteString and has the right length. Note, that the constructors also do the size check, i.e., there is a bit of redundancy.

Make Hash160/256.isValid() a static class method

---

compiler/src/main/java/io/neow3j/compiler/DebugInfo.java

VSCode column numbers and lines start at 1, thus the default column number should be set to 1 and not 0.

Change debug info default column numbers to 1

---

compiler/src/test-integration/java/io/neow3j/compiler/ByteStringIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/ECPointIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
compiler/src/test/java/io/neow3j/compiler/ManifestExtraTest.java
core/src/main/java/io/neow3j/script/OpCode.java
devpack/src/main/java/io/neow3j/devpack/ByteString.java
devpack/src/main/java/io/neow3j/devpack/ECPoint.java
devpack/src/main/java/io/neow3j/devpack/Hash160.java
devpack/src/main/java/io/neow3j/devpack/Hash256.java

- Removed size checks from constructors in `Hash160`, `Hash256` and `ECPoint` classes. 
- Added `ECPoint.isValid()` method.
- Added ByteString constructor from integer value.
Closes #699 #703

Hash and ECPoint improvements

---

core/src/main/java/io/neow3j/types/ContractParameter.java
core/src/test/java/io/neow3j/contract/ContractParameterTest.java

Resolves #700.
- Support automatic conversion of nested maps and lists to the corresponding ContractParameter types.
- Support automatic conversion of ECPublicKey and Sign.SignatureData to the corresponding ContractParameter using `mapToContractParameter`.
- Added static method ContractParameter.publicKey(ECPublicKey).

Support nested Map and List Objects in ContractParameter

---

compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
compiler/src/main/java/io/neow3j/compiler/converters/JumpsConverter.java
compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
compiler/src/test-integration/java/io/neow3j/compiler/AssertionIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/ECPointIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
compiler/src/test-integration/java/io/neow3j/compiler/TryCatchBlocksTest.java
compiler/src/test/java/io/neow3j/compiler/AssertionTest.java
compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
compiler/src/test/java/io/neow3j/compiler/ThrowExceptionTest.java
core/src/main/java/io/neow3j/script/OpCode.java

Closes #744.
The use of Java's `assert` statement is refactored, so that it is now handled as the equivalent of the NeoVM's opcode `ASSERT`.
Further:
- Messages can no longer be added to the `assert` statement, since NeoVM's `ASSERT` does not consume a message. The compiler throws a `CompilerException` if a message exists.
- A hard coded `assert false` statement or throwing a `new AssertionError()` results in a `CompilerException`.

Add support for NeoVM's ASSERT

---

compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
compiler/src/test-integration/java/io/neow3j/compiler/SwitchCaseIntegrationTest.java

The compiler failed compiling large switch-case constructs (more than 6 branches).

Fix handling of branch number in string switch-case compilation

---

compiler/src/main/java/io/neow3j/compiler/AsmHelper.java
compiler/src/test/java/io/neow3j/compiler/ContractEventsTest.java
devpack/src/main/java/io/neow3j/devpack/events/Event0Arg.java

Compilation for `Event` and `Event0Arg` failed.
I removed the latter because it was not intuitive to me when writing a contract.

Fix bug when in compilation of Event without any arguments

---

RELEASE.md
devpack/src/main/java/io/neow3j/devpack/contracts/ContractInterface.java
devpack/src/main/java/io/neow3j/devpack/contracts/NonFungibleToken.java
devpack/src/main/java/io/neow3j/devpack/contracts/Token.java
int-tests/src/test-integration/java/io/neow3j/compiler/ContractInterfaceIntegrationTest.java
int-tests/src/test-integration/java/io/neow3j/compiler/ContractTestRule.java
int-tests/src/test-integration/java/io/neow3j/compiler/DivisibleNFTIntegrationTest.java
int-tests/src/test-integration/java/io/neow3j/compiler/FungibleTokenTest.java
int-tests/src/test-integration/java/io/neow3j/compiler/NFTIntegrationTest.java
int-tests/src/test-integration/java/io/neow3j/compiler/NNSIntegrationTest.java
int-tests/src/test-integration/java/io/neow3j/compiler/NonDivisibleNFTIntegrationTest.java

With the recent changes, the NFT integration tests no longer need to statically set the deployed contract hash. With the changes in this PR, the contract hashes are now set dynamically and after a version bump, these tests no longer need separate updating.
Accordingly, I have updated the `RELEASE.md` which no longer needs this step.
Finally, I've removed the `abstract` modifier in the classes `ContractInterface`, `NonFungibleToken`, and `Token`. That way methods held by these classes can also be used without using/creating a specific subtype of them (e.g., `NonDivisibleNonFungibleToken` if it doesn't matter whether the called NFT is divisible or not...).

Update NFT integration tests

---

build.gradle
compiler/src/main/java/io/neow3j/compiler/Compiler.java
contract/src/main/java/io/neow3j/contract/ContractManagement.java
contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
contract/src/test/resources/responses/invocationresult_boolean_true.json
core/src/main/java/io/neow3j/protocol/core/response/NeoGetNep11Balances.java
core/src/main/java/io/neow3j/protocol/core/response/NeoGetNep17Balances.java
core/src/main/java/io/neow3j/protocol/core/response/NeoGetTokenBalances.java
core/src/test/java/io/neow3j/protocol/core/RequestTest.java
core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
devpack/src/main/java/io/neow3j/devpack/contracts/ContractManagement.java
int-tests/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
int-tests/src/test-integration/java/io/neow3j/contract/ContractManagementIntegrationTest.java
int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
test-tools/src/main/java/io/neow3j/test/NeoExpressTestContainer.java
test-tools/src/main/java/io/neow3j/test/NeoTestContainer.java
test-tools/src/main/resources/test.properties

Closes #854
Closes #855 
Closes #856

Updates for Neo version 3.4.0

---

core/src/main/java/io/neow3j/types/ContractParameter.java
core/src/test/java/io/neow3j/contract/ContractParameterTest.java

I had to fix this now, because it after all got more problematic for the GrantShares code.
Closes #887

Fix ContractParameter equals method

---

core/src/main/java/io/neow3j/protocol/core/response/NeoApplicationLog.java
core/src/main/java/io/neow3j/protocol/core/response/OracleResponse.java
core/src/main/java/io/neow3j/protocol/core/response/OracleResponseAttribute.java
core/src/main/java/io/neow3j/protocol/core/response/Transaction.java
core/src/main/java/io/neow3j/protocol/core/response/TransactionAttribute.java
core/src/main/java/io/neow3j/transaction/OracleResponseAttribute.java
core/src/test/java/io/neow3j/protocol/core/RequestTest.java
core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
core/src/test/java/io/neow3j/protocol/core/response/TransactionAttributeTest.java
core/src/test/java/io/neow3j/transaction/TransactionBuilderTest.java
core/src/test/java/io/neow3j/transaction/TransactionTest.java
int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jExpressIntegrationTest.java

Fixes #973 
Removed `io.neow3j.protocol.core.response.TransactionAttribute.fromType(TransactionAttributeType)`
It's replaced by the new `fromSerializable()` method
`io.neow3j.protocol.core.response.TransactionAttribute.fromSerializable(TransactionAttribute)`
`io.neow3j.protocol.core.responseOracleResponse(Integer, OracleResponseCode, String)`
👇🏼 
`io.neow3j.protocol.core.responseOracleResponse(BigInteger, OracleResponseCode, String)`

Fix from serializable method in Transaction DTO

---

devpack/src/main/java/io/neow3j/devpack/Storage.java
devpack/src/main/java/io/neow3j/devpack/StorageMap.java
int-tests/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java
int-tests/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java

Support `Hash160` and `Hash256` keys in storage delete methods

---

contract/src/main/java/io/neow3j/contract/PolicyContract.java
devpack/src/main/java/io/neow3j/devpack/constants/AttributeType.java
devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java
int-tests/src/test-integration/java/io/neow3j/compiler/PolicyContractIntegrationTest.java
int-tests/src/test-integration/java/io/neow3j/contract/PolicyContractIntegrationTest.java

Add new Policy attribute fee methods

---

compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
compiler/src/test/java/io/neow3j/compiler/PermissionManifestTest.java
compiler/src/test/java/io/neow3j/compiler/PlaceholderSubstitutionTest.java
compiler/src/test/java/io/neow3j/compiler/TrustManifestTest.java

Throw exception when other permissions are mixed with wildcard

---

gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jCompileTask.java
gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jPlugin.java
gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jPluginExtension.java
gradle-plugin/src/test-integration/java/io/neow3j/devpack/gradle/GradleProjectTestCase.java
gradle-plugin/src/test-integration/java/io/neow3j/devpack/gradle/Neow3jCompilePluginIntegrationTest.java
gradle-plugin/src/test-integration/java/io/neow3j/devpack/gradle/TestCaseUtils.java

#1016 
So @gsmachado I've followed your instructions, and I think this is the right way. I'm sure i dont understand 100% how it all happens, but Im getting along. Now I need to test this changes (specially the syntax around Spec), but I'm not quite sure how, running `./gradlew tests` or `./gradlew integrationTests` is failing, is there any setup needed? If so, where can I find it?

Make the output of `compileJava` an input of `neow3jCompile` to have a consistent caching behavior

---

devpack/build.gradle

Without having access to the _core_ module, developers using the devpack get warnings about undiscoverable enum values from OpCode and InteropService which are used in the devpack. Making the _core_ dependency transitive fixes the issue.
Here's how it looked like:

Make the "core" dependency in devpack transitive

---

devpack/build.gradle

Reverts neow3j/neow3j#1047
As we discussed in the daily, we should revert and then open an issue to properly implement a way to avoid developers to be confused with type of the core & SDK & devpack.

Revert "Make the "core" dependency in devpack transitive"

---

.github/workflows/release.yml

With these changes, the workflow dispatch input window will now look like the following:
@csmuller, I didn't get the reason for the comment on the snapshot run command on line 43 `# If you want to release a snapshot of gradle-plugin, remove the -x :gradle-plugin:publishToSonatype` since there is no `-x :gradle-plugin:publishToSonatype` there. I don't understand it in that context. Can you tell me what it's about?
Afaik, the snapshot release also publishes the gradle-plugin now (please correct me if I'm wrong). Do you think we should have an option of releasing a snapshot without the gradle-plugin? If not, I'll leave it like it is.

Improve GitHub workflow dispatch inputs

---

int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jExpressIntegrationTest.java
int-tests/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
test-tools/src/main/java/io/neow3j/test/NeoExpressTestContainer.java
test-tools/src/main/java/io/neow3j/test/TestBlockchain.java
test-tools/src/main/resources/test.properties
test-tools/src/test/java/io/neow3j/test/NeoExpressTestContainerTest.java

Neo express has changed how the `neo-express` file is read by default. Before v3.7.x, if no specific file was provided, the `default.neo-express` was expected in the working directory. With the release of 3.7.x, the default file is now expected in the absolute path `/root/.neo-express/default.neo-express`.
In the `neow3j-test-docker`, the `neo-express` file that is used to start a N3 blockchain is located in the absolute path `/neoxp/default.neo-express`. Thus, I adapted the `NeoExpressTestContainer` to use the `--input` flag when sending `neoxp` commands that require to be executed based on this running chain.
The behaviour of the existing methods does not change. There's no breaking change.
There is a new method `execNeoxpCommandWithDefaultConfig(String... commandParts)` which let's you …

Update test-tools for neo-express 3.7.6 changes

---

compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
compiler/src/test/java/io/neow3j/compiler/PermissionManifestTest.java

Fixes #1082 
This is a non-breaking change as it expands what is allowed.

Allow combined permissions if wildcard permission has specified methods
